### ISSUE TITLE
提供画面を注文番号順にソートする

### ISSUE THREAD

**Issue by Yayoi2078** [toririm/cafeore-2024#103]
## todo
- [x] #111
- [ ] 提供画面の subscription の QueryConstraint として`orderBy("orderId", "desc")`を追加する

## 内容
らいらいにバックエンド側の修正をやってもらったので、
`app/routes/master.tsx`での実装を参考に、提供の方も同じようにやってみてください

**Comment by toririm** [comment]
https://firebase.google.com/docs/firestore/query-data/order-limit-data?hl=ja
