### ISSUE TITLE
[/dashboard] 注文データ一覧ページをつくる

### ISSUE THREAD

**Issue by Yayoi2078** [toririm/cafeore-2024#106]
種類別の集計や、グラフなどがあると良い

todo
- [x] #147
- [x] #145 
- [x] #144 
- [x] #200

**Comment by toririm** [comment]
グラフ描画に使用するライブラリ

https://www.highcharts.com/

**Comment by toririm** [comment]
本体はこっちなんだけど
https://github.com/highcharts/highcharts

React で使用するためには下記ライブラリも必要っぽい
https://github.com/highcharts/highcharts-react

**Comment by toririm** [comment]
タスクが全て完了しており、最低限の動作をしているので
