### ISSUE TITLE
`itemRepository` を実装する

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#15]
### リポジトリパターンとは？
ソフトウェア設計のデザインパターンの一種
-  [DDDを実践するための手引き（リポジトリパターン編）](https://zenn.dev/kohii/articles/e4f325ed011db8)

### やること

- `app/repositories/item.ts` を編集して、アイテムの操作を実現する関数を書く
  - アイテムのモデルは `app/models/item.ts` にて定義されている
  - Firestore の使い方については基本的にはドキュメントを読もう！

# 変更点
@Lailai0477 
- #20 をマージした後に読むこと

### 変更前
```ts
export type ItemRepository = {
  findAll: () => Promise<Item[]>;
  findById: (id: string) => Promise<Item | null>;
  create: (data: Item) => Promise<void>;
  update: (data: Item) => Promise<void>;
  delete: (id: string) => Promise<void>;
};
```

### 変更後
```ts
export type ItemRepository = {
  save(data: Item): Promise<ItemWithId>;
  delete(id: string): Promise<void>;
  findById(id: string): Promise<ItemWithId | null>;
};
```
### `Item` と `ItemWithId` の違い
```ts
const type Item = {
  id?: string; // id は存在しなくてもよい
  name: string;
  price: number;
  type: 'hot' | 'ice' | 'ore' | 'milk'
}
```

```ts
const type ItemWithId = {
  id: string; // ここも必須
  name: string;
  price: number;
  type: 'hot' | 'ice' | 'ore' | 'milk'
}
```

使い分け
- `id` は Firestore によって自動生成されるので、新規作成する際は `Item` を `save` に渡して `ItemWithId` が返ってくる

### `save` とは
引数の`data`に
- **`id`が存在する** のとき 新規アイテムを作成する
  - `addDoc()` を使う
- **`id`が存在しない** のとき　`id`に紐づいたアイテムを上書きする
  - `setDoc()` を使う

[ここら辺](https://firebase.google.com/docs/firestore/manage-data/add-data?hl=ja&authuser=0#add_a_document)を読むといい

型で判別するというよりは、プロパティの `id` が存在するかどうかで分岐する（[ヒント](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn)）

### `delete`, `findById`
そのままです。

`findById` に関しては、クエリは必要なくてそのまま`getDoc()`してやればいいです（[ヒント](https://firebase.google.com/docs/firestore/query-data/get-data?hl=ja&authuser=0#get_a_document)）

### `findAll` はいらないの？
~はい~
いいえ、普通に必要だったのでオーダーリポジトリでは実装してます。ごめん🙇

**Comment by Lailai0477** [comment]
@toririm 

> ### `save` とは
> 引数の`data`に
> 
> * **`id`が存在する** のとき 新規アイテムを作成する
>   
>   * `addDoc()` を使う
> * **`id`が存在しない** のとき　`id`に紐づいたアイテムを上書きする
>   
>   * `setDoc()` を使う
> 
> [ここら辺](https://firebase.google.com/docs/firestore/manage-data/add-data?hl=ja&authuser=0#add_a_document)を読むといい
> 
> 型で判別するというよりは、プロパティの `id` が存在するかどうかで分岐する（[ヒント](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn)）

これのidが存在するときと存在しないときが逆なのかなと思ったんですがどうでしょうか…？

**Comment by toririm** [comment]
@Lailai0477 
普通に逆でした……
ご指摘のとおりです。
ありがとうございます
