### ISSUE TITLE
ネットワークステータス表示コンポーネントを作る

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#23]
障害に備えて全画面に実装する

https://ja.react.dev/learn/reusing-logic-with-custom-hooks

**Comment by toririm** [comment]
SATO RYOより
> ちっちゃいアイコンのステータスより、いっそ、オフラインになったら、全画面操作不能状態にしてしまうのも手では？

**Comment by takum1-me** [comment]
オフラインだったらページ変える？
それだったらroot.tsxに雑にonline statusをinputする

**Comment by takum1-me** [comment]
それでできるんか知らんけど
