### ISSUE TITLE
/casher 指名欄の修正

### ISSUE THREAD

**Issue by Astalum** [toririm/cafeore-2024#241]
データ型の null ではなく 文字列の null を入れる

**Comment by toririm** [comment]
これ、もしかしたら共通処理で解決できるかも（その方が望ましい）しれないので、一旦優先度低めで大丈夫です

**Comment by toririm** [comment]
割引優先でお願いします🙏

また、共通処理の部分の実装をお任せするかもしれません。指示が細かくなってつまらないかもしれないけど、私もみんな使うことになると思うので、お願いできればと
