### ISSUE TITLE
pos /serve オーダー準備完了ボタン

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#256]
### Must be resolved before this issue
- [x] #315

準備完了→提供済み
の2段階にする

**Comment by takum1-me** [comment]
これってどっかで議論に上がったんだっけ？

**Comment by toririm** [comment]
上がってないが、仮に客のスマホで呼び出しをやることになったら必要になる状態なので、、

**Comment by takum1-me** [comment]
あねあね、OK

**Comment by toririm** [comment]
duplicate #321
