### ISSUE TITLE
pos レジ客向け小さい画面のデザイン案作成

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#257]
スマホ相当　と　iPad相当
の2種類あるとよい

合計金額や割引、アイテムの情報をレジと同期

- [x] スマホ画面の作成 #340 
- [x] タブレット画面の作成 #341

**Comment by takum1-me** [comment]
雑につくってみてもいい？

**Comment by takum1-me** [comment]
OKならどこに作ればいいかファイル名教えて欲しい（mobile/app/route/casher.tsx?)

**Comment by toririm** [comment]
`pos/app/routes/cashier-mini.tsx`

**Comment by Astalum** [comment]
- [ ] スマホ画面の作成
- [ ] タブレット画面の作成

**Comment by toririm** [comment]
一旦close
