### ISSUE TITLE
/serve 直近の提供情報が画面の端に表示されるようにする

### ISSUE THREAD

**Issue by Yayoi2078** [toririm/cafeore-2024#285]
直近3オーダー分くらいの情報が右下あたりにいい感じに表示されるようにする
#284 の提供取消しボタンもここにつける

**Comment by toririm** [comment]
https://ui.shadcn.com/docs/components/toast

これとか使えたらよさそう

**Comment by toririm** [comment]
あーでもすぐ消えない方がいいか

**Comment by Yayoi2078** [comment]
これをベースに消える条件だけいじれないですかね？
