### ISSUE TITLE
レジ　マイグレーション

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#313]
## 目的
ボタン操作のレジとキーボード操作のレジを統合していく。
どちらの操作方法でもある程度の操作を実現できるようにする。

## 比較
ここで比較した内容を元に、デザインをブラッシュアップしていく

### ボタン
Good
- 見たら操作方法がわかる

Bad
- 指名入力に自由度がない
  - レジが「ドリッパーの `n`th が誰か」知っている必要がある
- 結局数字入力ではキーボードを使う必要がある

### キーボード
Good
- キーボードだけですべての操作が完結する
- 指名が自由記述

Bad
- 初見だと操作がわかりにくい

## 方針
比較でのいいとこ取りをしていく。
デザインなども better な案があれば改善していく

ロジック部分は、v2でしっかり作ってあるのでそっちをベースにすると楽かも

**Comment by toririm** [comment]
いっかい打ち合わせをしよう

**Comment by Astalum** [comment]
おkです、いつにします？
