### ISSUE TITLE
レジ画面を作成する

### ISSUE THREAD

**Issue by Yayoi2078** [toririm/cafeore-2024#4]
### やること
`app/routes/casher.tsx` でレジ画面の見た目を作成する

### todo
- [x] #115 
- [x] #169

**Comment by Astalum** [comment]
金銭授受関係の画面を作成、pr作成済み

**Comment by Astalum** [comment]
h1タグなり認識されてないのはなぜでしょう

**Comment by toririm** [comment]
@Astalum 
h1タグの文字がそんなに大きくなってないことを指しているのだと仮定します。

今回はTailwindを使用しているので、**デフォルトではすべてのスタイルが共通化されています**
つまり、h1もh3もpもspanもすべての要素の文字が同じサイズに表示されています（スタイルと構造の独立）
文字の大きさを変えたい場合は別途tailwindの機能をつかって指定する必要があります

**Comment by Astalum** [comment]
たけとさんからのコメント
- マスターは早めに注文内容を知りたい
    - 注文確定した時点で飛ばす
    - アラート画面で金額入力してお釣り自動で表示かなぁ
        - 計算させるとミスりそうなので僕はお釣り表示したい
        - たけとさんは計算させて入力の手間を減らしたいらしい

**Comment by toririm** [comment]
レジ画面自体はできてるのでclose
