### ISSUE TITLE
オーダー情報のリアルタイム同期に対応する

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#40]
### 概要
現在 `route/_header.serve.tsx` は `clientLoader` からオーダーを取得している
しかし、この方法ではオーダー情報がリアルタイムに更新されない
提供画面ではリアルタイムでオーダーの情報が更新されていてほしいので、修正する

### やり方
`route/items/route.tsx`の`useSWRSubscription`を使ったやり方でオーダーを取得すると、リアルタイム更新される情報を取得できる
オーダーとアイテムで多少異なるものの、コードを読んでうまく実装してほしい

この場合、`clientLoader`は不要になる

**Comment by takum1-me** [comment]
直接話した！
内容：任せた！任された！
