### ISSUE TITLE
`routes/orders.tsx`のリファクタリング

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#82]
### 概要
`routes/items`と同じノリでファイル分割＆Action分割をやる

**Comment by Lailai0477** [comment]
@toririm これって`break;`無くても大丈夫ですっけ…
```
export const action: ClientActionFunction = async (args) => {
  const { request } = args;
  switch (request.method) {
    case "POST":
      return addItem(args);
    case "DELETE":
      return deleteItem(args);
    default:
      console.error("Invalid method", request.method);
      return new Response(null, { status: 405 });
  }
};
```

**Comment by toririm** [comment]
> @toririm これって`break;`無くても大丈夫ですっけ…
> 
> ```
> 
> export const action: ClientActionFunction = async (args) => {
> 
>   const { request } = args;
> 
>   switch (request.method) {
> 
>     case "POST":
> 
>       return addItem(args);
> 
>     case "DELETE":
> 
>       return deleteItem(args);
> 
>     default:
> 
>       console.error("Invalid method", request.method);
> 
>       return new Response(null, { status: 405 });
> 
>   }
> 
> };
> 
> ```
> 
> 

returnで関数が終わるので、大丈夫です👌

**Comment by Lailai0477** [comment]
確かに、ありがとうございます
