### ISSUE TITLE
アイテム管理ページでアイテムを簡単に削除できないようにする

### ISSUE THREAD

**Issue by toririm** [toririm/cafeore-2024#93]
確認画面をはさむとか、IDを再入力させるとか、間違って削除されないようにしたい

**Comment by takum1-me** [comment]
正味、削除はDBを触れる人だけが直接行える、ぐらいでも耐えそうな気はしてる

**Comment by toririm** [comment]
> 削除はDBを触れる人だけが直接行える、ぐらいでも耐えそう

これは思ってた。でもせっかくUI作ったのもあるし、暇だったらやってみてね～みたいなニュアンスです
実用的な意味を考えると、セールとかの動的な価格設定が可能かも（実際やるかはおいておいて）

**Comment by takum1-me** [comment]
あねあね、いい話

**Comment by toririm** [comment]
- ref #291
