### ISSUE TITLE
提供画面の見やすさ向上

### ISSUE THREAD

**Issue by takum1-me** [toririm/cafeore-2024#94]
Cardコンポーネントなどを使用し、注文をわかりやすく表示するとともに、各カップのstatusなどの可視化をしたい

**Comment by toririm** [comment]
カップのステータスはまだデータとして持ってないので、`model`も変更してやる必要がある。
ただ、そこに関しては別のPRでやってほしい。PRは小さいほうがいいので。

**Comment by toririm** [comment]
issueの分割が必要
